# Generated migration for Little Sisters of the Poor - Mombasa (Upgraded)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/%Y/%m/')),
                ('category', models.CharField(choices=[('elders','Elders'),('volunteers','Volunteers'),('events','Events'),('facilities','Facilities'),('community','Community'),('other','Other')], default='other', max_length=20)),
                ('photographer', models.CharField(blank=True, max_length=100)),
                ('date_taken', models.DateField(default=django.utils.timezone.now)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-date_uploaded'], 'verbose_name_plural': 'Photos'},
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_email', models.EmailField()),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('method', models.CharField(choices=[('mpesa','M-Pesa'),('bank','Bank Transfer'),('crypto','Cryptocurrency'),('paypal','PayPal'),('card','Credit/Debit Card'),('other','Other')], max_length=20)),
                ('frequency', models.CharField(choices=[('once','One-Time'),('monthly','Monthly'),('quarterly','Quarterly'),('annual','Annual')], default='once', max_length=20)),
                ('status', models.CharField(choices=[('pending','Pending'),('completed','Completed'),('failed','Failed'),('refunded','Refunded')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-donated_at']},
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('skills', models.CharField(choices=[('healthcare','Healthcare'),('cooking','Cooking'),('cleaning','Cleaning'),('teaching','Teaching'),('administrative','Administrative'),('counseling','Counseling'),('maintenance','Maintenance'),('music','Music & Entertainment'),('it','IT & Technology'),('other','Other')], max_length=50)),
                ('motivation', models.TextField()),
                ('availability', models.CharField(max_length=200)),
                ('preferred_activities', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('registered','Registered'),('active','Active'),('inactive','Inactive'),('vetted','Background Vetted')], default='registered', max_length=20)),
                ('background_check_completed', models.BooleanField(default=False)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('hours_contributed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
            ],
            options={'ordering': ['-joined_date']},
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/')),
                ('content', models.TextField()),
                ('excerpt', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('draft','Draft'),('published','Published'),('archived','Archived')], default='draft', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('allow_comments', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField()),
                ('request_type', models.CharField(choices=[('health','Health'),('family','Family'),('work','Work/Employment'),('financial','Financial'),('spiritual','Spiritual'),('thanksgiving','Thanksgiving'),('other','Other')], max_length=20)),
                ('intention', models.TextField()),
                ('is_for_self', models.BooleanField(default=True)),
                ('who_for', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending','Pending'),('approved','Approved'),('rejected','Rejected'),('answered','Answered')], default='pending', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('answered_on', models.DateTimeField(blank=True, null=True)),
                ('answer_note', models.TextField(blank=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ServiceAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('mass','Mass'),('rosary','Rosary'),('visitation','Visitation Hours'),('event','Special Event'),('novena','Novena')], max_length=20)),
                ('description', models.TextField()),
                ('day_of_week', models.CharField(blank=True, max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('quote', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('interest', models.CharField(choices=[('volunteering','Volunteering / AJJ'),('corporate','Corporate Partnership'),('inkind','In-Kind Donations'),('admissions','Admissions / Elder Care'),('vocation','Religious Vocation'),('general','General Inquiry')], default='general', max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('birthday','Birthday Celebration'),('mass','Special Mass'),('fundraiser','Fundraiser'),('community','Community Day'),('training','Volunteer Training'),('other','Other')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(default='Little Sisters of the Poor, Tudor', max_length=200)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['date', 'start_time']},
        ),
        # Indexes
        migrations.AddIndex(model_name='photo', index=models.Index(fields=['-date_uploaded'], name='photo_date_uploaded_idx')),
        migrations.AddIndex(model_name='photo', index=models.Index(fields=['category'], name='photo_category_idx')),
        migrations.AddIndex(model_name='photo', index=models.Index(fields=['featured'], name='photo_featured_idx')),
        migrations.AddIndex(model_name='donation', index=models.Index(fields=['-donated_at'], name='donation_donated_at_idx')),
        migrations.AddIndex(model_name='donation', index=models.Index(fields=['status'], name='donation_status_idx')),
        migrations.AddIndex(model_name='blogpost', index=models.Index(fields=['-published_at'], name='blogpost_published_at_idx')),
        migrations.AddIndex(model_name='blogpost', index=models.Index(fields=['slug'], name='blogpost_slug_idx')),
        migrations.AddIndex(model_name='contactmessage', index=models.Index(fields=['is_read'], name='contact_is_read_idx')),
        migrations.AddIndex(model_name='event', index=models.Index(fields=['date'], name='event_date_idx')),
    ]
