# This file is auto-generated by Django
# Run: python manage.py makemigrations
# This will create actual migration files

# To create migrations manually if needed:
# python manage.py makemigrations core
# python manage.py migrate
